# Generated by Django 6.0.2 on 2026-02-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_workerprofile_service_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workerprofile",
            name="service_category",
            field=models.CharField(
                choices=[
                    ("Plumber", "Plumber"),
                    ("Electrician", "Electrician"),
                    ("Cleaner", "Cleaner"),
                    ("Carpenter", "Carpenter"),
                ],
                max_length=20,
            ),
        ),
    ]
