# Generated by Django 5.2 on 2026-03-20 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_workerprofile_service_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="current_latitude",
            field=models.DecimalField(
                blank=True, db_index=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="current_longitude",
            field=models.DecimalField(
                blank=True, db_index=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="workerdocument",
            name="document_number",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="workerdocument",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Verified", "Verified"),
                    ("Rejected", "Rejected"),
                ],
                db_index=True,
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="workerprofile",
            name="availability_status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Inactive", "Inactive"),
                    ("Busy", "Busy"),
                ],
                db_index=True,
                default="Inactive",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="workerprofile",
            name="service_category",
            field=models.CharField(
                choices=[
                    ("Plumber", "Plumber"),
                    ("Electrician", "Electrician"),
                    ("Cleaner", "Cleaner"),
                    ("Carpenter", "Carpenter"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="workerprofile",
            name="service_latitude",
            field=models.DecimalField(
                blank=True, db_index=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="workerprofile",
            name="service_longitude",
            field=models.DecimalField(
                blank=True, db_index=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="workerprofile",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Verified", "Verified"),
                    ("Rejected", "Rejected"),
                ],
                db_index=True,
                default="Pending",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="workerdocument",
            index=models.Index(
                fields=["worker_profile", "verification_status"],
                name="accounts_wo_worker__22073c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workerdocument",
            index=models.Index(
                fields=["uploaded_at"], name="accounts_wo_uploade_2bdcc3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workerprofile",
            index=models.Index(
                fields=["verification_status", "availability_status"],
                name="accounts_wo_verific_36dbbe_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workerprofile",
            index=models.Index(
                fields=["service_category", "availability_status"],
                name="accounts_wo_service_f64074_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workerprofile",
            index=models.Index(
                fields=["average_rating"], name="accounts_wo_average_5282bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workerprofile",
            index=models.Index(
                fields=["created_at"], name="accounts_wo_created_a3dbed_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="savedlocation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("user_profile",),
                name="unique_default_location_per_user",
            ),
        ),
    ]
