# Generated by Django 5.2 on 2026-03-20 05:02

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0004_alter_userprofile_current_latitude_and_more"),
        ("services", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkerReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("review_text", models.TextField(blank=True)),
                (
                    "moderation_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worker_review",
                        to="services.servicerequest",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submitted_worker_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_reviews",
                        to="accounts.workerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewSentiment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        choices=[
                            ("POSITIVE", "Positive"),
                            ("NEUTRAL", "Neutral"),
                            ("NEGATIVE", "Negative"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("compound_score", models.DecimalField(decimal_places=4, max_digits=5)),
                ("confidence", models.DecimalField(decimal_places=4, max_digits=5)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "review",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentiment",
                        to="ratings.workerreview",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkerRecommendationScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "raw_average_rating",
                    models.DecimalField(decimal_places=3, default=0, max_digits=4),
                ),
                ("total_reviews", models.PositiveIntegerField(default=0)),
                (
                    "bayesian_rating",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                (
                    "average_sentiment_compound",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                (
                    "sentiment_adjustment",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                (
                    "average_distance_km",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="Rolling distance average for completed nearby jobs.",
                        max_digits=8,
                    ),
                ),
                (
                    "distance_component",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                (
                    "recommendation_score",
                    models.DecimalField(
                        db_index=True, decimal_places=4, default=0, max_digits=7
                    ),
                ),
                ("rank_last_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "worker",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_score",
                        to="accounts.workerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-recommendation_score"],
                "indexes": [
                    models.Index(
                        fields=["recommendation_score", "rank_last_updated_at"],
                        name="ratings_wor_recomme_54b1c5_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="workerreview",
            index=models.Index(
                fields=["worker", "created_at"], name="ratings_wor_worker__d348d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workerreview",
            index=models.Index(
                fields=["worker", "rating"], name="ratings_wor_worker__2a4da6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="workerreview",
            constraint=models.UniqueConstraint(
                fields=("reviewer", "worker", "request"),
                name="unique_review_per_request",
            ),
        ),
        migrations.AddIndex(
            model_name="reviewsentiment",
            index=models.Index(
                fields=["label", "processed_at"], name="ratings_rev_label_7d955a_idx"
            ),
        ),
    ]
