# Generated by Django 5.2 on 2026-04-07 05:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ratings", "0002_workerreview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workerreview",
            name="rating",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
    ]
