# Generated by Django 5.2 on 2026-04-28 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ratings", "0005_enforce_unique_review_per_worker"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="workerreview",
            name="unique_review_per_worker",
        ),
        migrations.RemoveField(
            model_name="reviewsentiment",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="workerrecommendationscore",
            name="average_distance_km",
        ),
        migrations.RemoveField(
            model_name="workerrecommendationscore",
            name="distance_component",
        ),
    ]
