# Generated by Django 5.2 on 2026-04-28 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ratings", "0006_remove_workerreview_unique_review_per_worker_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewsentiment",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
