# Generated by Django 5.2 on 2026-04-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ratings", "0007_reviewsentiment_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="workerrecommendationscore",
            name="average_distance_km",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="workerrecommendationscore",
            name="distance_component",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
    ]
