# Generated by Django 5.2 on 2026-03-20 05:02

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0004_alter_userprofile_current_latitude_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=140)),
                ("description", models.TextField(blank=True)),
                (
                    "budget_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=9, null=True
                    ),
                ),
                (
                    "budget_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=9, null=True
                    ),
                ),
                (
                    "request_latitude",
                    models.DecimalField(db_index=True, decimal_places=6, max_digits=9),
                ),
                (
                    "request_longitude",
                    models.DecimalField(db_index=True, decimal_places=6, max_digits=9),
                ),
                ("request_address", models.CharField(blank=True, max_length=255)),
                (
                    "search_radius_km",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0.2),
                            django.core.validators.MaxValueValidator(50.0),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("MATCHING", "Matching"),
                            ("ASSIGNED", "Assigned"),
                            ("ARRIVING", "Arriving"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("expected_start_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_worker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_requests",
                        to="accounts.workerprofile",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_requests",
                        to="services.servicecategory",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ServiceRequestBroadcast",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SENT", "Sent"),
                            ("VIEWED", "Viewed"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("EXPIRED", "Expired"),
                        ],
                        db_index=True,
                        default="SENT",
                        max_length=20,
                    ),
                ),
                (
                    "distance_km",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=8,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "ranking_score",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broadcasts",
                        to="services.servicerequest",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_broadcasts",
                        to="accounts.workerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ServiceRequestEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested"),
                            ("BROADCASTED", "Broadcasted"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("ARRIVING", "Arriving"),
                            ("STARTED", "Started"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("detail", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_request_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="services.servicerequest",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ServiceRouteSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "origin_latitude",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                (
                    "origin_longitude",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                (
                    "destination_latitude",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                (
                    "destination_longitude",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                (
                    "estimated_distance_km",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True
                    ),
                ),
                (
                    "estimated_duration_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("route_polyline", models.TextField(blank=True)),
                ("map_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_snapshot",
                        to="services.servicerequest",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="servicerequest",
            index=models.Index(
                fields=["status", "category"], name="services_se_status_d77774_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequest",
            index=models.Index(
                fields=["requester", "status"], name="services_se_request_67e7a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequest",
            index=models.Index(
                fields=["created_at"], name="services_se_created_fe46d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequestbroadcast",
            index=models.Index(
                fields=["worker", "status"], name="services_se_worker__9900cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequestbroadcast",
            index=models.Index(
                fields=["request", "status"], name="services_se_request_7ccf60_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequestbroadcast",
            index=models.Index(
                fields=["ranking_score"], name="services_se_ranking_cded57_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="servicerequestbroadcast",
            constraint=models.UniqueConstraint(
                fields=("request", "worker"),
                name="unique_broadcast_per_worker_per_request",
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequestevent",
            index=models.Index(
                fields=["request", "created_at"], name="services_se_request_90cfc0_idx"
            ),
        ),
    ]
