# Generated by Django 5.2 on 2026-04-24 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_seed_default_categories"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ServiceRouteSnapshot",
        ),
    ]
