# Generated by Django 5.2 on 2026-04-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_delete_serviceroutesnapshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicerequestevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("REQUESTED", "Requested"),
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                    ("ARRIVING", "Arriving"),
                    ("STARTED", "Started"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="ServiceRequestBroadcast",
        ),
    ]
